Fix admin for concierge 4.0 beta
concierge/admin pull request #1
Opened 2016-10-29 10:51 UTC by Awarua-

2016-10-29 22:38 UTC, drkno requested changes

2016-10-29 22:38 UTC, mrkno commented on admin.js
> -    helpHook = function (moduleName, origionalHelp, config) {
So help messages are no longer filtered?

2016-10-29 22:38 UTC, mrkno commented on admin.js
> +    cfg = this.config;
`exports.config` is safer if the this context cannot be bound

2016-11-26 09:22 UTC, Awarua- commented on admin.js
> -    helpHook = function (moduleName, origionalHelp, config) {
I don't remember why this is, but probably a good reasone

2017-03-26 07:22 UTC, Awarua- commented on admin.js
> +    cfg = this.config;
Changed

2017-03-26 07:22 UTC, Awarua- commented on admin.js
> -    helpHook = function (moduleName, origionalHelp, config) {
Added back

2017-03-26 07:24 UTC, merged